# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-26 15:10
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_unixdatetimefield.fields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('email_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='emailuser',
            name='user',
        ),
        migrations.RemoveField(
            model_name='event',
            name='recur',
        ),
        migrations.RemoveField(
            model_name='recipient',
            name='email_user',
        ),
        migrations.AddField(
            model_name='notification',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='notification',
            name='event',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='email_app.Event'),
        ),
        migrations.AddField(
            model_name='notification',
            name='is_active',
            field=models.CharField(choices=[('Y', 'ACTIVE'), ('N', 'INACTIVE')], default='Y', max_length=1),
        ),
        migrations.AddField(
            model_name='notification',
            name='max_repeats',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='notification',
            name='next_notify_date',
            field=django_unixdatetimefield.fields.UnixDateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='notification',
            name='notify_count',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='notification',
            name='recipient',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='email_app.Recipient'),
        ),
        migrations.AddField(
            model_name='notification',
            name='recurrance',
            field=models.IntegerField(choices=[(86400, 'DAILY'), (604800, 'WEEKLY'), (2629746, 'MONTHLY'), (31557600, 'YEARLY')], default=31557600),
        ),
        migrations.AddField(
            model_name='notification',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='notification',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='recipient',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='EmailUser',
        ),
        migrations.DeleteModel(
            name='Recur',
        ),
    ]
